CC   := gcc
CCLD := gcc

bin = grpar


all: $(bin)

$(bin): $(bin).o
	$(CCLD) $(LDFLAGS) -o $@ $^

%.o: %.c
	$(CC) -c -O2 -Wall -fno-strict-aliasing $(CFLAGS) $(CPPFLAGS) -o $@ $^

clean:
	rm -f $(bin) $(bin).o

